# Use the official MySQL image from the Docker Hub
FROM mysql:latest

# Set environment variables for the MySQL root user password, database, and user
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=db_naturasso
ENV MYSQL_USER=db_user
ENV MYSQL_PASSWORD=1234

# Expose the default MySQL port
EXPOSE 3306